apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-lab-prod
  namespace: app-prod
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: app-prod
      app.kubernetes.io/name: devops-lab
  endpoints:
    - port: http
      path: /metrics
      interval: 15s