name: CD Dev (GitOps)

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write   # trengs for å committe tilbake

jobs:
  build_push_and_bump_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-lab:${{ steps.vars.outputs.TAG }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/devops-lab:${{ steps.vars.outputs.TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/devops-lab:latest

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-lab:${{ steps.vars.outputs.TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-lab:latest

      - name: Update Helm values-dev.yaml image tag
        run: |
          sed -i "s/^  tag: .*/  tag: \"${{ steps.vars.outputs.TAG }}\"/" deploy/charts/devops-lab/values-dev.yaml
          cat deploy/charts/devops-lab/values-dev.yaml | head -n 30

      - name: Commit and push change
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add deploy/charts/devops-lab/values-dev.yaml
          git commit -m "chore(dev): bump image tag to ${{ steps.vars.outputs.TAG }}" || echo "No changes to commit"
          git push